// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sbuqsebscroourrxohvw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNidXFzZWJzY3Jvb3VycnhvaHZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzMDQyMTcsImV4cCI6MjA1ODg4MDIxN30.7mnxdLt-aVl5pw3mF_1VmS9CGUYaFCKs1gZ6P8okawY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);